import { Document } from "./document";

export type Category = {
    /**
     * Unique ID generated by the server for the category. This is used as an identifier.
     */
    category_id: string;

    /**
     * Category title
     */
    name: string;

    /**
     * Parent category ID for current category. Has the value of "-1" for "root" categories.
     */
    parent_category_id: string;

    /**
     * Depth level of the category within category tree
     */
    depth: number;

    visibility: boolean;
    show_in_menu: boolean;

    /**
     * Category order position within siblings
     */

    sibling_order: number;
    created_time: string;

    /**
     * Whether the category has items in it
     */
    has_active_items: boolean;

    document_id: string;
    documents: Document[];
};
